"""create processing tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-06 11:56:29.219630

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_key", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('processing','completed','failed')",
            name=op.f("ck_idempotency_records_state"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_idempotency_records_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "user_id",
            "endpoint_key",
            "idempotency_key",
            name="uq_idempotency_scope_key",
        ),
    )
    op.create_table(
        "processing_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_type", sa.String(length=60), nullable=False),
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("retry_of_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("owner_scope_type", sa.String(length=30), nullable=False),
        sa.Column("owner_scope_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.String(length=30), server_default="pending", nullable=False
        ),
        sa.Column("current_stage", sa.String(length=60), nullable=True),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.Column("total_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("success_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "progress_percent",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "cancel_requested",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "input_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("enqueued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(owner_scope_type = 'admin_global' AND owner_scope_id IS NULL) "
            "OR (owner_scope_type IN ('user','recruitment_project') "
            "AND owner_scope_id IS NOT NULL)",
            name=op.f("ck_processing_runs_owner_scope_id"),
        ),
        sa.CheckConstraint(
            "owner_scope_type IN ('user','recruitment_project','admin_global')",
            name=op.f("ck_processing_runs_owner_scope_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','enqueue_failed','running','waiting_review',"
            "'cancel_requested','completed','failed','cancelled')",
            name=op.f("ck_processing_runs_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND max_attempts >= 1",
            name=op.f("ck_processing_runs_attempts"),
        ),
        sa.CheckConstraint(
            "processed_count >= 0 AND processed_count <= total_count",
            name=op.f("ck_processing_runs_processed_count"),
        ),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100",
            name=op.f("ck_processing_runs_progress"),
        ),
        sa.CheckConstraint(
            "success_count >= 0 AND failed_count >= 0",
            name=op.f("ck_processing_runs_result_counts"),
        ),
        sa.CheckConstraint(
            "total_count >= 0", name=op.f("ck_processing_runs_total_count")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_processing_runs_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_processing_runs_retry_of_run_id_processing_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_runs")),
    )
    op.create_index(
        "ix_processing_runs_creator_created",
        "processing_runs",
        ["created_by_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_processing_runs_pending",
        "processing_runs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending','enqueue_failed')"),
    )
    op.create_index(
        "ix_processing_runs_running_heartbeat",
        "processing_runs",
        ["heartbeat_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "ix_processing_runs_scope_created",
        "processing_runs",
        ["owner_scope_type", "owner_scope_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_processing_runs_subject_created",
        "processing_runs",
        ["subject_type", "subject_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "processing_errors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=False),
        sa.Column("item_type", sa.String(length=50), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("item_key", sa.String(length=200), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_runs.id"],
            name=op.f("fk_processing_errors_run_id_processing_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_errors")),
    )
    op.create_index(
        "ix_processing_errors_run_occurred",
        "processing_errors",
        ["run_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_processing_errors_run_stage_retryable",
        "processing_errors",
        ["run_id", "stage", "retryable"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_audit_logs_processing_run_id_processing_runs"),
        "audit_logs",
        "processing_runs",
        ["processing_run_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_audit_logs_processing_run_id_processing_runs"),
        "audit_logs",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_processing_errors_run_stage_retryable", table_name="processing_errors"
    )
    op.drop_index("ix_processing_errors_run_occurred", table_name="processing_errors")
    op.drop_table("processing_errors")
    op.drop_index("ix_processing_runs_subject_created", table_name="processing_runs")
    op.drop_index("ix_processing_runs_scope_created", table_name="processing_runs")
    op.drop_index(
        "ix_processing_runs_running_heartbeat",
        table_name="processing_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_processing_runs_pending",
        table_name="processing_runs",
        postgresql_where=sa.text("status IN ('pending','enqueue_failed')"),
    )
    op.drop_index("ix_processing_runs_creator_created", table_name="processing_runs")
    op.drop_table("processing_runs")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
