"""create market import tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-06 13:23:12.830592

"""

from collections.abc import Sequence
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("adapter_code", sa.String(length=80), nullable=False),
        sa.Column("adapter_version", sa.String(length=40), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column(
            "is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('file_import','crawler','manual')",
            name=op.f("ck_data_sources_source_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("code", name=op.f("uq_data_sources_code")),
    )
    data_sources = sa.table(
        "data_sources",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("adapter_code", sa.String()),
        sa.column("adapter_version", sa.String()),
        sa.column("source_type", sa.String()),
        sa.column("is_enabled", sa.Boolean()),
        sa.column("config", postgresql.JSONB()),
    )
    op.bulk_insert(
        data_sources,
        [
            {
                "id": UUID("00000000-0000-4000-8000-000000000001"),
                "code": "standard",
                "display_name": "Standard",
                "adapter_code": "standard_v1",
                "adapter_version": "1",
                "source_type": "file_import",
                "is_enabled": True,
                "config": {},
            },
            {
                "id": UUID("00000000-0000-4000-8000-000000000002"),
                "code": "liepin",
                "display_name": "Liepin",
                "adapter_code": "liepin_v1",
                "adapter_version": "1",
                "source_type": "file_import",
                "is_enabled": True,
                "config": {},
            },
            {
                "id": UUID("00000000-0000-4000-8000-000000000003"),
                "code": "zhilian",
                "display_name": "Zhilian",
                "adapter_code": "zhilian_v1",
                "adapter_version": "1",
                "source_type": "file_import",
                "is_enabled": True,
                "config": {},
            },
            {
                "id": UUID("00000000-0000-4000-8000-000000000004"),
                "code": "zhilian_direct",
                "display_name": "Zhilian Direct",
                "adapter_code": "zhilian_v1",
                "adapter_version": "1",
                "source_type": "file_import",
                "is_enabled": True,
                "config": {},
            },
        ],
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("detected_adapter_code", sa.String(length=80), nullable=True),
        sa.Column("adapter_version", sa.String(length=40), nullable=True),
        sa.Column("schema_version", sa.String(length=40), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default="uploaded", nullable=False
        ),
        sa.Column("total_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("accepted_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rejected_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("warning_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "batch_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('uploaded','processing','processed','partial','failed',"
            "'archived')",
            name=op.f("ck_import_batches_status"),
        ),
        sa.CheckConstraint(
            "accepted_rows + rejected_rows <= total_rows",
            name=op.f("ck_import_batches_resolved_counts"),
        ),
        sa.CheckConstraint(
            "total_rows >= 0 AND accepted_rows >= 0 AND rejected_rows >= 0 "
            "AND warning_rows >= 0",
            name=op.f("ck_import_batches_nonnegative_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_import_batches_file_id_stored_files"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_import_batches_source_id_data_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_import_batches_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        "ix_import_batches_created",
        "import_batches",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_import_batches_source_collected",
        "import_batches",
        ["source_id", sa.literal_column("collected_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_import_batches_status_created",
        "import_batches",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "raw_job_postings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("source_code", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=150), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("job_name", sa.Text(), nullable=False),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("salary_text", sa.Text(), nullable=True),
        sa.Column("work_area_text", sa.Text(), nullable=True),
        sa.Column("city_text", sa.Text(), nullable=True),
        sa.Column("education_text", sa.Text(), nullable=True),
        sa.Column("work_year_text", sa.Text(), nullable=True),
        sa.Column("issue_date_text", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "source_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_encoding", sa.String(length=30), nullable=True),
        sa.Column(
            "parse_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(job_name)) > 0",
            name=op.f("ck_raw_job_postings_nonempty_job_name"),
        ),
        sa.CheckConstraint(
            "row_number >= 1", name=op.f("ck_raw_job_postings_positive_row_number")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_raw_job_postings_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_job_postings")),
        sa.UniqueConstraint("batch_id", "row_number", name="uq_raw_job_batch_row"),
    )
    op.create_index(
        "ix_raw_job_batch_row",
        "raw_job_postings",
        ["batch_id", "row_number"],
        unique=False,
    )
    op.create_index(
        "ix_raw_job_content_hash",
        "raw_job_postings",
        ["content_hash"],
        unique=False,
        postgresql_where=sa.text("content_hash IS NOT NULL"),
    )
    op.create_index(
        "ix_raw_job_source_external",
        "raw_job_postings",
        ["source_code", "external_id"],
        unique=False,
    )
    op.create_index(
        "ix_raw_job_source_url",
        "raw_job_postings",
        ["source_url"],
        unique=False,
        postgresql_where=sa.text("source_url IS NOT NULL"),
    )
    op.create_table(
        "normalized_job_postings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_job_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("normalization_version", sa.String(length=80), nullable=False),
        sa.Column("normalized_title", sa.String(length=300), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=True),
        sa.Column("city_code", sa.String(length=30), nullable=True),
        sa.Column("city_name", sa.String(length=100), nullable=True),
        sa.Column("work_area", sa.String(length=200), nullable=True),
        sa.Column("salary_min_monthly", sa.Integer(), nullable=True),
        sa.Column("salary_max_monthly", sa.Integer(), nullable=True),
        sa.Column("salary_months", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("education_level", sa.String(length=30), nullable=True),
        sa.Column("experience_min_months", sa.Integer(), nullable=True),
        sa.Column("experience_max_months", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "quality_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("duplicate_of_id", sa.Uuid(), nullable=True),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_by_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "experience_max_months IS NULL OR "
            "experience_max_months >= experience_min_months",
            name=op.f("ck_normalized_job_postings_experience_range"),
        ),
        sa.CheckConstraint(
            "experience_min_months IS NULL OR experience_min_months >= 0",
            name=op.f("ck_normalized_job_postings_experience_min"),
        ),
        sa.CheckConstraint(
            "quality_score BETWEEN 0 AND 100",
            name=op.f("ck_normalized_job_postings_quality_score"),
        ),
        sa.CheckConstraint(
            "salary_max_monthly IS NULL OR salary_max_monthly >= salary_min_monthly",
            name=op.f("ck_normalized_job_postings_salary_range"),
        ),
        sa.CheckConstraint(
            "salary_min_monthly IS NULL OR salary_min_monthly >= 0",
            name=op.f("ck_normalized_job_postings_salary_min"),
        ),
        sa.CheckConstraint(
            "version_no >= 1", name=op.f("ck_normalized_job_postings_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_normalized_job_postings_created_by_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_normalized_job_postings_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["normalized_job_postings.id"],
            name=op.f(
                "fk_normalized_job_postings_duplicate_of_id_normalized_job_postings"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_job_id"],
            ["raw_job_postings.id"],
            name=op.f("fk_normalized_job_postings_raw_job_id_raw_job_postings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_job_postings")),
        sa.UniqueConstraint(
            "raw_job_id", "version_no", name="uq_normalized_job_version"
        ),
    )
    op.create_index(
        "ix_normalized_job_city_published",
        "normalized_job_postings",
        ["city_code", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_normalized_job_duplicate",
        "normalized_job_postings",
        ["duplicate_of_id"],
        unique=False,
    )
    op.create_index(
        "ix_normalized_job_published",
        "normalized_job_postings",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_normalized_job_quality",
        "normalized_job_postings",
        [sa.literal_column("quality_score DESC")],
        unique=False,
    )
    op.create_index(
        "uq_normalized_job_current",
        "normalized_job_postings",
        ["raw_job_id"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_normalized_job_current",
        table_name="normalized_job_postings",
        postgresql_where=sa.text("is_current = true"),
    )
    op.drop_index("ix_normalized_job_quality", table_name="normalized_job_postings")
    op.drop_index("ix_normalized_job_published", table_name="normalized_job_postings")
    op.drop_index("ix_normalized_job_duplicate", table_name="normalized_job_postings")
    op.drop_index(
        "ix_normalized_job_city_published", table_name="normalized_job_postings"
    )
    op.drop_table("normalized_job_postings")
    op.drop_index(
        "ix_raw_job_source_url",
        table_name="raw_job_postings",
        postgresql_where=sa.text("source_url IS NOT NULL"),
    )
    op.drop_index("ix_raw_job_source_external", table_name="raw_job_postings")
    op.drop_index(
        "ix_raw_job_content_hash",
        table_name="raw_job_postings",
        postgresql_where=sa.text("content_hash IS NOT NULL"),
    )
    op.drop_index("ix_raw_job_batch_row", table_name="raw_job_postings")
    op.drop_table("raw_job_postings")
    op.drop_index("ix_import_batches_status_created", table_name="import_batches")
    op.drop_index("ix_import_batches_source_collected", table_name="import_batches")
    op.drop_index("ix_import_batches_created", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
