"""create catalog skeleton tables

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-06 14:09:32.787716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deprecated')", name=op.f("ck_domains_status")
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name=op.f("ck_domains_not_self_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["domains.id"], name=op.f("fk_domains_parent_id_domains")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domains")),
        sa.UniqueConstraint("code", name="uq_domains_code"),
    )
    op.create_index(
        "ix_domains_parent_sort", "domains", ["parent_id", "sort_order"], unique=False
    )
    op.create_table(
        "capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("skill_type", sa.String(length=40), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="candidate", nullable=False
        ),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("replacement_capability_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','deprecated')",
            name=op.f("ck_capabilities_status"),
        ),
        sa.CheckConstraint(
            "length(btrim(canonical_name)) > 0",
            name=op.f("ck_capabilities_nonempty_name"),
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
            name=op.f("fk_capabilities_domain_id_domains"),
        ),
        sa.ForeignKeyConstraint(
            ["replacement_capability_id"],
            ["capabilities.id"],
            name=op.f("fk_capabilities_replacement_capability_id_capabilities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capabilities")),
        sa.UniqueConstraint(
            "domain_id", "canonical_name", name="uq_capabilities_domain_name"
        ),
    )
    op.create_index(
        "ix_capabilities_domain_status",
        "capabilities",
        ["domain_id", "status"],
        unique=False,
    )
    op.create_table(
        "catalog_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','validated','published','archived')",
            name=op.f("ck_catalog_versions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_catalog_versions_created_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_versions")),
        sa.UniqueConstraint("version_no", name="uq_catalog_versions_version_no"),
    )
    op.create_index(
        "uq_catalog_versions_current_published",
        "catalog_versions",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("status = 'published' AND is_current = true"),
    )
    op.create_table(
        "job_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="candidate", nullable=False
        ),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("replacement_job_role_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('candidate','active','deprecated')",
            name=op.f("ck_job_roles_status"),
        ),
        sa.CheckConstraint(
            "length(btrim(canonical_name)) > 0", name=op.f("ck_job_roles_nonempty_name")
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["domains.id"], name=op.f("fk_job_roles_domain_id_domains")
        ),
        sa.ForeignKeyConstraint(
            ["replacement_job_role_id"],
            ["job_roles.id"],
            name=op.f("fk_job_roles_replacement_job_role_id_job_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_roles")),
        sa.UniqueConstraint(
            "domain_id", "canonical_name", name="uq_job_roles_domain_name"
        ),
    )
    op.create_table(
        "capability_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deprecated','ambiguous')",
            name=op.f("ck_capability_aliases_status"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_capability_aliases_capability_id_capabilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_aliases")),
        sa.UniqueConstraint("alias", name="uq_capability_aliases_alias"),
    )
    op.create_table(
        "catalog_imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("import_type", sa.String(length=30), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('validate_only','apply')", name=op.f("ck_catalog_imports_mode")
        ),
        sa.CheckConstraint(
            "status IN ('processing','validated','applied','failed')",
            name=op.f("ck_catalog_imports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_catalog_imports_file_id_stored_files"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_catalog_imports_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_imports")),
    )
    op.create_table(
        "catalog_version_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("catalog_version_id", sa.Uuid(), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=True),
        sa.Column("job_role_id", sa.Uuid(), nullable=True),
        sa.Column("change_type", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(item_type = 'capability' AND capability_id IS NOT NULL "
            "AND job_role_id IS NULL) OR (item_type = 'job_role' "
            "AND capability_id IS NULL AND job_role_id IS NOT NULL)",
            name=op.f("ck_catalog_version_items_one_target"),
        ),
        sa.CheckConstraint(
            "item_type IN ('capability','job_role')",
            name=op.f("ck_catalog_version_items_item_type"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_catalog_version_items_capability_id_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["catalog_version_id"],
            ["catalog_versions.id"],
            name=op.f("fk_catalog_version_items_catalog_version_id_catalog_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_role_id"],
            ["job_roles.id"],
            name=op.f("fk_catalog_version_items_job_role_id_job_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_version_items")),
        sa.UniqueConstraint(
            "catalog_version_id",
            "item_type",
            "capability_id",
            "job_role_id",
            name="uq_catalog_version_items_target",
        ),
    )
    op.create_table(
        "job_role_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_role_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_role_id"],
            ["job_roles.id"],
            name=op.f("fk_job_role_aliases_job_role_id_job_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_role_aliases")),
        sa.UniqueConstraint("alias", name="uq_job_role_aliases_alias"),
    )
    op.create_table(
        "catalog_import_rows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("catalog_import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("row_status", sa.String(length=20), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["catalog_import_id"],
            ["catalog_imports.id"],
            name=op.f("fk_catalog_import_rows_catalog_import_id_catalog_imports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_import_rows")),
    )
    op.create_index(
        "ix_catalog_import_rows_import_row",
        "catalog_import_rows",
        ["catalog_import_id", "row_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_catalog_import_rows_import_row", table_name="catalog_import_rows")
    op.drop_table("catalog_import_rows")
    op.drop_table("job_role_aliases")
    op.drop_table("catalog_version_items")
    op.drop_table("catalog_imports")
    op.drop_table("capability_aliases")
    op.drop_table("job_roles")
    op.drop_index(
        "uq_catalog_versions_current_published",
        table_name="catalog_versions",
        postgresql_where=sa.text("status = 'published' AND is_current = true"),
    )
    op.drop_table("catalog_versions")
    op.drop_index("ix_capabilities_domain_status", table_name="capabilities")
    op.drop_table("capabilities")
    op.drop_index("ix_domains_parent_sort", table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
