"""create discovery tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-06 15:07:46.527256

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("processing_run_id", sa.Uuid(), nullable=False),
        sa.Column("input_batch_ids", sa.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("current_catalog_version_id", sa.Uuid(), nullable=True),
        sa.Column("algorithm_version", sa.String(length=80), nullable=False),
        sa.Column("extraction_version", sa.String(length=80), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed','cancelled')",
            name=op.f("ck_discovery_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_discovery_runs_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["current_catalog_version_id"],
            ["catalog_versions.id"],
            name=op.f("fk_discovery_runs_current_catalog_version_id_catalog_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_discovery_runs_processing_run_id_processing_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_runs")),
        sa.UniqueConstraint(
            "processing_run_id", name="uq_discovery_runs_processing_run"
        ),
    )
    op.create_index(
        "ix_discovery_runs_created",
        "discovery_runs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_discovery_runs_status_created",
        "discovery_runs",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "skill_combination_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discovery_run_id", sa.Uuid(), nullable=False),
        sa.Column("suggested_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column(
            "definition_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("support_job_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("company_count", sa.Integer(), nullable=False),
        sa.Column("support_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("diversity_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("coherence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("novelty_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("evidence_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "overall_candidate_score", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('candidate','feedback_collected','proposed_for_review',"
            "'rejected')",
            name=op.f("ck_skill_combination_candidates_status"),
        ),
        sa.CheckConstraint(
            "coherence_score BETWEEN 0 AND 1",
            name=op.f("ck_skill_combination_candidates_coherence_score"),
        ),
        sa.CheckConstraint(
            "company_count >= 0",
            name=op.f("ck_skill_combination_candidates_company_count"),
        ),
        sa.CheckConstraint(
            "diversity_score BETWEEN 0 AND 1",
            name=op.f("ck_skill_combination_candidates_diversity_score"),
        ),
        sa.CheckConstraint(
            "evidence_score BETWEEN 0 AND 1",
            name=op.f("ck_skill_combination_candidates_evidence_score"),
        ),
        sa.CheckConstraint(
            "length(btrim(suggested_name)) > 0",
            name=op.f("ck_skill_combination_candidates_nonempty_name"),
        ),
        sa.CheckConstraint(
            "novelty_score BETWEEN 0 AND 1",
            name=op.f("ck_skill_combination_candidates_novelty_score"),
        ),
        sa.CheckConstraint(
            "overall_candidate_score BETWEEN 0 AND 1",
            name=op.f("ck_skill_combination_candidates_overall_candidate_score"),
        ),
        sa.CheckConstraint(
            "source_count >= 0",
            name=op.f("ck_skill_combination_candidates_source_count"),
        ),
        sa.CheckConstraint(
            "support_job_count >= 0",
            name=op.f("ck_skill_combination_candidates_support_job_count"),
        ),
        sa.CheckConstraint(
            "support_score BETWEEN 0 AND 1",
            name=op.f("ck_skill_combination_candidates_support_score"),
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["discovery_runs.id"],
            name=op.f(
                "fk_skill_combination_candidates_discovery_run_id_discovery_runs"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_combination_candidates")),
        sa.UniqueConstraint(
            "discovery_run_id",
            "normalized_name",
            name="uq_skill_combination_candidates_run_name",
        ),
    )
    op.create_index(
        "ix_skill_combination_candidates_run_score",
        "skill_combination_candidates",
        ["discovery_run_id", sa.literal_column("overall_candidate_score DESC")],
        unique=False,
    )
    op.create_index(
        "ix_skill_combination_candidates_status",
        "skill_combination_candidates",
        ["status"],
        unique=False,
    )
    op.create_table(
        "combination_skills",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("skill_role", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("frequency", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.CheckConstraint(
            "skill_role IN ('core','bonus')",
            name=op.f("ck_combination_skills_skill_role"),
        ),
        sa.CheckConstraint(
            "frequency BETWEEN 0 AND 1", name=op.f("ck_combination_skills_frequency")
        ),
        sa.CheckConstraint(
            "weight BETWEEN 0 AND 1", name=op.f("ck_combination_skills_weight")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["skill_combination_candidates.id"],
            name=op.f(
                "fk_combination_skills_candidate_id_skill_combination_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_combination_skills_capability_id_capabilities"),
        ),
        sa.PrimaryKeyConstraint(
            "candidate_id", "capability_id", name=op.f("pk_combination_skills")
        ),
    )
    op.create_table(
        "combination_evidence",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_job_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_weight", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "representative",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_weight BETWEEN 0 AND 1",
            name=op.f("ck_combination_evidence_evidence_weight"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["skill_combination_candidates.id"],
            name=op.f(
                "fk_combination_evidence_candidate_id_skill_combination_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["normalized_job_id"],
            ["normalized_job_postings.id"],
            name=op.f(
                "fk_combination_evidence_normalized_job_id_normalized_job_postings"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "candidate_id", "normalized_job_id", name=op.f("pk_combination_evidence")
        ),
    )
    op.create_table(
        "job_analysis_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("normalized_job_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), server_default="1", nullable=False),
        sa.Column("extraction_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "structured_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "validation_errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('candidate','validated','invalid')",
            name=op.f("ck_job_analysis_profiles_status"),
        ),
        sa.CheckConstraint(
            "version_no >= 1", name=op.f("ck_job_analysis_profiles_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_job_analysis_profiles_created_by_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["normalized_job_id"],
            ["normalized_job_postings.id"],
            name=op.f(
                "fk_job_analysis_profiles_normalized_job_id_normalized_job_postings"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_analysis_profiles")),
        sa.UniqueConstraint(
            "normalized_job_id",
            "extraction_version",
            name="uq_job_analysis_profiles_job_extraction",
        ),
        sa.UniqueConstraint(
            "normalized_job_id",
            "version_no",
            name="uq_job_analysis_profiles_job_version",
        ),
    )
    op.create_index(
        "ix_job_analysis_profiles_status",
        "job_analysis_profiles",
        ["status"],
        unique=False,
    )
    op.create_table(
        "job_skill_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_profile_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=True),
        sa.Column("raw_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("requirement_type", sa.String(length=20), nullable=False),
        sa.Column("importance", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("required_level", sa.String(length=20), nullable=True),
        sa.Column("mapping_method", sa.String(length=30), nullable=False),
        sa.Column("mapping_status", sa.String(length=20), nullable=False),
        sa.Column("extraction_source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(mapping_status = 'mapped') = (capability_id IS NOT NULL)",
            name=op.f("ck_job_skill_candidates_mapping_capability"),
        ),
        sa.CheckConstraint(
            "extraction_source IN ('algorithm','llm','merged','manual')",
            name=op.f("ck_job_skill_candidates_extraction_source"),
        ),
        sa.CheckConstraint(
            "mapping_method IN ('canonical_exact','alias_exact','normalized_exact',"
            "'semantic_candidate','manual','unmapped')",
            name=op.f("ck_job_skill_candidates_mapping_method"),
        ),
        sa.CheckConstraint(
            "mapping_status IN ('mapped','ambiguous','unmapped','invalid')",
            name=op.f("ck_job_skill_candidates_mapping_status"),
        ),
        sa.CheckConstraint(
            "required_level IS NULL OR required_level IN "
            "('beginner','intermediate','advanced')",
            name=op.f("ck_job_skill_candidates_required_level"),
        ),
        sa.CheckConstraint(
            "requirement_type IN ('required','preferred')",
            name=op.f("ck_job_skill_candidates_requirement_type"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1",
            name=op.f("ck_job_skill_candidates_confidence"),
        ),
        sa.CheckConstraint(
            "importance BETWEEN 0 AND 1",
            name=op.f("ck_job_skill_candidates_importance"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_profile_id"],
            ["job_analysis_profiles.id"],
            name=op.f(
                "fk_job_skill_candidates_analysis_profile_id_job_analysis_profiles"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_job_skill_candidates_capability_id_capabilities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_skill_candidates")),
        sa.UniqueConstraint(
            "analysis_profile_id",
            "normalized_name",
            name="uq_job_skill_candidates_profile_name",
        ),
    )
    op.create_index(
        "ix_job_skill_candidates_capability",
        "job_skill_candidates",
        ["capability_id"],
        unique=False,
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.create_index(
        "ix_job_skill_candidates_mapping_created",
        "job_skill_candidates",
        ["mapping_status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_job_skill_candidates_profile_requirement",
        "job_skill_candidates",
        ["analysis_profile_id", "requirement_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_job_skill_candidates_profile_requirement", table_name="job_skill_candidates"
    )
    op.drop_index(
        "ix_job_skill_candidates_mapping_created", table_name="job_skill_candidates"
    )
    op.drop_index(
        "ix_job_skill_candidates_capability",
        table_name="job_skill_candidates",
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.drop_table("job_skill_candidates")
    op.drop_index("ix_job_analysis_profiles_status", table_name="job_analysis_profiles")
    op.drop_table("job_analysis_profiles")
    op.drop_table("combination_evidence")
    op.drop_table("combination_skills")
    op.drop_index(
        "ix_skill_combination_candidates_status",
        table_name="skill_combination_candidates",
    )
    op.drop_index(
        "ix_skill_combination_candidates_run_score",
        table_name="skill_combination_candidates",
    )
    op.drop_table("skill_combination_candidates")
    op.drop_index("ix_discovery_runs_status_created", table_name="discovery_runs")
    op.drop_index("ix_discovery_runs_created", table_name="discovery_runs")
    op.drop_table("discovery_runs")
    # ### end Alembic commands ###
