"""create resume profile tables

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-06 23:47:41.719670

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | Sequence[str] | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "source_language",
            sa.String(length=20),
            server_default="zh-CN",
            nullable=False,
        ),
        sa.Column(
            "parse_status",
            sa.String(length=30),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column("latest_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(parse_status = 'archived') = (archived_at IS NOT NULL)",
            name=op.f("ck_resumes_archived_at"),
        ),
        sa.CheckConstraint(
            "parse_status IN ('uploaded','processing','ready','failed','archived')",
            name=op.f("ck_resumes_parse_status"),
        ),
        sa.CheckConstraint(
            "created_by_user_id = owner_user_id",
            name=op.f("ck_resumes_creator_is_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_resumes_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_resumes_file_id_stored_files"),
        ),
        sa.ForeignKeyConstraint(
            ["latest_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_resumes_latest_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_resumes_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
        sa.UniqueConstraint("file_id", name="uq_resumes_file_id"),
    )
    op.create_index(
        "ix_resumes_owner_created",
        "resumes",
        ["owner_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_resumes_status_updated",
        "resumes",
        ["parse_status", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_table(
        "resume_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column("base_profile_id", sa.Uuid(), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("extraction_version", sa.String(length=80), nullable=False),
        sa.Column("profile_source", sa.String(length=20), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("text_extraction_method", sa.String(length=20), nullable=False),
        sa.Column("highest_education_level", sa.String(length=30), nullable=True),
        sa.Column("total_experience_months", sa.Integer(), nullable=True),
        sa.Column(
            "structured_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(profile_source = 'extracted' AND created_by_run_id IS NOT NULL "
            "AND base_profile_id IS NULL) OR "
            "(profile_source = 'manual_revision' AND created_by_run_id IS NULL "
            "AND base_profile_id IS NOT NULL)",
            name=op.f("ck_resume_profiles_source_links"),
        ),
        sa.CheckConstraint(
            "(profile_source = 'extracted' AND "
            "status IN ('candidate','confirmed','superseded')) OR "
            "(profile_source = 'manual_revision' AND "
            "status IN ('draft','confirmed','superseded'))",
            name=op.f("ck_resume_profiles_source_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('confirmed','superseded')) = (confirmed_at IS NOT NULL)",
            name=op.f("ck_resume_profiles_confirmed_at"),
        ),
        sa.CheckConstraint(
            "profile_source IN ('extracted','manual_revision')",
            name=op.f("ck_resume_profiles_profile_source"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate','draft','confirmed','superseded')",
            name=op.f("ck_resume_profiles_status"),
        ),
        sa.CheckConstraint(
            "text_extraction_method IN ('pdf_text','docx')",
            name=op.f("ck_resume_profiles_extraction_method"),
        ),
        sa.CheckConstraint(
            "base_profile_id IS NULL OR base_profile_id <> id",
            name=op.f("ck_resume_profiles_not_self_base"),
        ),
        sa.CheckConstraint(
            "total_experience_months IS NULL OR total_experience_months >= 0",
            name=op.f("ck_resume_profiles_experience_months"),
        ),
        sa.CheckConstraint(
            "version_no >= 1", name=op.f("ck_resume_profiles_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["base_profile_id"],
            ["resume_profiles.id"],
            name=op.f("fk_resume_profiles_base_profile_id_resume_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_resume_profiles_created_by_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_resume_profiles_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_resume_profiles_resume_id_resumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_profiles")),
        sa.UniqueConstraint(
            "resume_id", "version_no", name="uq_resume_profiles_version"
        ),
    )
    op.create_index(
        "ix_resume_profiles_resume_version",
        "resume_profiles",
        ["resume_id", sa.literal_column("version_no DESC")],
        unique=False,
    )
    op.create_index(
        "uq_resume_profiles_confirmed",
        "resume_profiles",
        ["resume_id"],
        unique=True,
        postgresql_where=sa.text("status = 'confirmed'"),
    )
    op.create_index(
        "uq_resume_profiles_extraction",
        "resume_profiles",
        ["resume_id", "extraction_version"],
        unique=True,
        postgresql_where=sa.text("profile_source = 'extracted'"),
    )
    op.create_table(
        "resume_skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=True),
        sa.Column("raw_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("proficiency", sa.String(length=20), nullable=True),
        sa.Column("explicit_experience_months", sa.Integer(), nullable=True),
        sa.Column("evidence_strength", sa.String(length=20), nullable=False),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column("evidence_start", sa.Integer(), nullable=True),
        sa.Column("evidence_end", sa.Integer(), nullable=True),
        sa.Column("mapping_method", sa.String(length=30), nullable=False),
        sa.Column("mapping_status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "user_confirmed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(mapping_status = 'mapped' AND mapping_method IN "
            "('canonical_exact','alias_exact','manual')) OR "
            "(mapping_status = 'unmapped' AND mapping_method = 'unmapped')",
            name=op.f("ck_resume_skills_mapping_combination"),
        ),
        sa.CheckConstraint(
            "(mapping_status = 'mapped') = (capability_id IS NOT NULL)",
            name=op.f("ck_resume_skills_mapping_target"),
        ),
        sa.CheckConstraint(
            "(source = 'llm' AND evidence_quote IS NOT NULL "
            "AND evidence_start IS NOT NULL AND evidence_end IS NOT NULL "
            "AND user_confirmed = false) OR "
            "(source = 'manual' AND user_confirmed = true)",
            name=op.f("ck_resume_skills_source_evidence"),
        ),
        sa.CheckConstraint(
            "(source = 'llm' AND mapping_method IN "
            "('canonical_exact','alias_exact','unmapped')) OR "
            "(source = 'manual' AND mapping_method IN ('manual','unmapped'))",
            name=op.f("ck_resume_skills_source_mapping"),
        ),
        sa.CheckConstraint(
            "evidence_strength IN ('mention','project','work')",
            name=op.f("ck_resume_skills_evidence_strength"),
        ),
        sa.CheckConstraint(
            "mapping_method IN ('canonical_exact','alias_exact','manual','unmapped')",
            name=op.f("ck_resume_skills_mapping_method"),
        ),
        sa.CheckConstraint(
            "mapping_status IN ('mapped','unmapped')",
            name=op.f("ck_resume_skills_mapping_status"),
        ),
        sa.CheckConstraint(
            "proficiency IS NULL OR "
            "proficiency IN ('beginner','intermediate','advanced')",
            name=op.f("ck_resume_skills_proficiency"),
        ),
        sa.CheckConstraint(
            "source IN ('llm','manual')", name=op.f("ck_resume_skills_source")
        ),
        sa.CheckConstraint(
            "(evidence_start IS NULL AND evidence_end IS NULL) OR "
            "(evidence_start >= 0 AND evidence_end > evidence_start)",
            name=op.f("ck_resume_skills_evidence_offsets"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_resume_skills_confidence")
        ),
        sa.CheckConstraint(
            "explicit_experience_months IS NULL OR explicit_experience_months >= 0",
            name=op.f("ck_resume_skills_experience_months"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_resume_skills_capability_id_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["resume_profiles.id"],
            name=op.f("fk_resume_skills_profile_id_resume_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_skills")),
        sa.UniqueConstraint(
            "profile_id", "normalized_name", name="uq_resume_skills_name"
        ),
    )
    op.create_index(
        "ix_resume_skills_capability",
        "resume_skills",
        ["capability_id"],
        unique=False,
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.create_index(
        "ix_resume_skills_mapping",
        "resume_skills",
        ["profile_id", "mapping_status"],
        unique=False,
    )
    op.create_index(
        "uq_resume_skills_profile_capability",
        "resume_skills",
        ["profile_id", "capability_id"],
        unique=True,
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_resume_skills_profile_capability",
        table_name="resume_skills",
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.drop_index("ix_resume_skills_mapping", table_name="resume_skills")
    op.drop_index(
        "ix_resume_skills_capability",
        table_name="resume_skills",
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.drop_table("resume_skills")
    op.drop_index(
        "uq_resume_profiles_extraction",
        table_name="resume_profiles",
        postgresql_where=sa.text("profile_source = 'extracted'"),
    )
    op.drop_index(
        "uq_resume_profiles_confirmed",
        table_name="resume_profiles",
        postgresql_where=sa.text("status = 'confirmed'"),
    )
    op.drop_index("ix_resume_profiles_resume_version", table_name="resume_profiles")
    op.drop_table("resume_profiles")
    op.drop_index("ix_resumes_status_updated", table_name="resumes")
    op.drop_index("ix_resumes_owner_created", table_name="resumes")
    op.drop_table("resumes")
    # ### end Alembic commands ###
