"""create file tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-06 11:55:01.230490

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=150), nullable=False),
        sa.Column("extension", sa.String(length=20), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("scan_status", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('market_jd','catalog','resume','jd','portfolio','other')",
            name=op.f("ck_stored_files_category"),
        ),
        sa.CheckConstraint(
            "scan_status IN ('pending','clean','rejected','not_required')",
            name=op.f("ck_stored_files_scan_status"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded','attached','archived','deleted')",
            name=op.f("ck_stored_files_status"),
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_stored_files_positive_size")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_stored_files_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_stored_files_storage_key")),
    )
    op.create_index(
        "ix_stored_files_expiring_unattached",
        "stored_files",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'uploaded' AND expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_stored_files_hash_size",
        "stored_files",
        ["sha256", "size_bytes"],
        unique=False,
    )
    op.create_index(
        "ix_stored_files_uploader_created",
        "stored_files",
        ["uploaded_by_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "file_access_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('preview','download')", name=op.f("ck_file_access_logs_action")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_files.id"],
            name=op.f("fk_file_access_logs_file_id_stored_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_file_access_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_access_logs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_access_logs")
    op.drop_index("ix_stored_files_uploader_created", table_name="stored_files")
    op.drop_index("ix_stored_files_hash_size", table_name="stored_files")
    op.drop_index(
        "ix_stored_files_expiring_unattached",
        table_name="stored_files",
        postgresql_where=sa.text("status = 'uploaded' AND expires_at IS NOT NULL"),
    )
    op.drop_table("stored_files")
    # ### end Alembic commands ###
