"""create review tables

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-06 16:04:07.361607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_change_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("change_type", sa.String(length=40), nullable=False),
        sa.Column(
            "proposed_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type = 'create_job_role'",
            name=op.f("ck_graph_change_candidates_change_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence_summary) = 'object'",
            name=op.f("ck_graph_change_candidates_evidence_summary_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(proposed_payload) = 'object'",
            name=op.f("ck_graph_change_candidates_proposed_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(source_snapshot) = 'object'",
            name=op.f("ck_graph_change_candidates_source_snapshot_object"),
        ),
        sa.CheckConstraint(
            "review_status IN ('pending','needs_revision','approved','rejected')",
            name=op.f("ck_graph_change_candidates_review_status"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1",
            name=op.f("ck_graph_change_candidates_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_graph_change_candidates_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_graph_change_candidates_reviewed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["skill_combination_candidates.id"],
            name=op.f(
                "fk_graph_change_candidates_source_candidate_id_skill_combination_candidates"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_change_candidates")),
        sa.UniqueConstraint(
            "source_candidate_id", name="uq_graph_change_candidates_source_candidate"
        ),
    )
    op.create_index(
        "ix_graph_change_candidates_status_created",
        "graph_change_candidates",
        ["review_status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("graph_change_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column(
            "before_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "after_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approve','revise','reject')",
            name=op.f("ck_review_decisions_decision"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(after_payload) = 'object'",
            name=op.f("ck_review_decisions_after_payload_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(before_payload) = 'object'",
            name=op.f("ck_review_decisions_before_payload_object"),
        ),
        sa.ForeignKeyConstraint(
            ["graph_change_candidate_id"],
            ["graph_change_candidates.id"],
            name=op.f(
                "fk_review_decisions_graph_change_candidate_id_graph_change_candidates"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_review_decisions_reviewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    op.create_index(
        "ix_review_decisions_candidate_created",
        "review_decisions",
        ["graph_change_candidate_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_review_decisions_candidate_created", table_name="review_decisions"
    )
    op.drop_table("review_decisions")
    op.drop_index(
        "ix_graph_change_candidates_status_created",
        table_name="graph_change_candidates",
    )
    op.drop_table("graph_change_candidates")
    # ### end Alembic commands ###
