"""create graph publication tables

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-06 16:42:11.522796

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_graph_change_candidates_review_status"),
        "graph_change_candidates",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_graph_change_candidates_review_status"),
        "graph_change_candidates",
        "review_status IN "
        "('pending','needs_revision','approved','rejected','published')",
    )
    op.create_table(
        "graph_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("source_proposal_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_version_id", sa.Uuid(), nullable=False),
        sa.Column("job_role_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'published') = (published_at IS NOT NULL)",
            name=op.f("ck_graph_versions_published_at"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(snapshot) = 'object'",
            name=op.f("ck_graph_versions_snapshot_object"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','publishing','published','failed')",
            name=op.f("ck_graph_versions_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_graph_versions_attempt_count")
        ),
        sa.CheckConstraint(
            "version_no >= 1", name=op.f("ck_graph_versions_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["catalog_version_id"],
            ["catalog_versions.id"],
            name=op.f("fk_graph_versions_catalog_version_id_catalog_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_graph_versions_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["source_proposal_id"],
            ["graph_change_candidates.id"],
            name=op.f("fk_graph_versions_source_proposal_id_graph_change_candidates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_versions")),
        sa.UniqueConstraint(
            "catalog_version_id", name="uq_graph_versions_catalog_version"
        ),
        sa.UniqueConstraint("job_role_id", name="uq_graph_versions_job_role"),
        sa.UniqueConstraint(
            "source_proposal_id", name="uq_graph_versions_source_proposal"
        ),
        sa.UniqueConstraint("version_no", name="uq_graph_versions_version_no"),
    )
    op.create_index(
        "ix_graph_versions_status_created",
        "graph_versions",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_graph_versions_current_published",
        "graph_versions",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("status = 'published' AND is_current = true"),
    )
    op.create_table(
        "job_role_capabilities",
        sa.Column("job_role_id", sa.Uuid(), nullable=False),
        sa.Column("capability_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_type", sa.String(length=20), nullable=False),
        sa.Column("importance", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("source_candidate_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requirement_type IN ('required','bonus')",
            name=op.f("ck_job_role_capabilities_requirement_type"),
        ),
        sa.CheckConstraint(
            "importance BETWEEN 0 AND 1",
            name=op.f("ck_job_role_capabilities_importance"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_job_role_capabilities_capability_id_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["job_role_id"],
            ["job_roles.id"],
            name=op.f("fk_job_role_capabilities_job_role_id_job_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_candidate_id"],
            ["graph_change_candidates.id"],
            name=op.f(
                "fk_job_role_capabilities_source_candidate_id_graph_change_candidates"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "job_role_id", "capability_id", name=op.f("pk_job_role_capabilities")
        ),
    )
    op.create_index(
        "ix_job_role_capabilities_capability_type",
        "job_role_capabilities",
        ["capability_id", "requirement_type"],
        unique=False,
    )
    op.add_column(
        "job_roles",
        sa.Column(
            "definition_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_job_roles_definition_payload_object"),
        "job_roles",
        "jsonb_typeof(definition_payload) = 'object'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_job_roles_definition_payload_object"), "job_roles", type_="check"
    )
    op.drop_column("job_roles", "definition_payload")
    op.drop_index(
        "ix_job_role_capabilities_capability_type", table_name="job_role_capabilities"
    )
    op.drop_table("job_role_capabilities")
    op.drop_index(
        "uq_graph_versions_current_published",
        table_name="graph_versions",
        postgresql_where=sa.text("status = 'published' AND is_current = true"),
    )
    op.drop_index("ix_graph_versions_status_created", table_name="graph_versions")
    op.drop_table("graph_versions")
    op.drop_constraint(
        op.f("ck_graph_change_candidates_review_status"),
        "graph_change_candidates",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_graph_change_candidates_review_status"),
        "graph_change_candidates",
        "review_status IN ('pending','needs_revision','approved','rejected')",
    )
    # ### end Alembic commands ###
