import { useState } from 'react'
import { ArrowRightOutlined, CloudUploadOutlined, TeamOutlined } from '@ant-design/icons'
import { FrameCorners } from '../components/FrameCorners'
import { confirmRecruitmentRequirements, createRecruitmentMatchRun, createRecruitmentProject, getProcessingRun, getRecruitmentProject, listRecruitmentMatchResults, submitRecruitmentJd, uploadRecruitmentCandidates } from '../services/resumeWorkflowApi'

export default function HRWorkspacePage() {
  const [title, setTitle] = useState('')
  const [jd, setJd] = useState('')
  const [files, setFiles] = useState<File[]>([])
  const [projectId, setProjectId] = useState<string | null>(null)
  const [status, setStatus] = useState('等待 JD')
  const [result, setResult] = useState<any>(null)
  const waitRun = async (runId: string) => { for (;;) { const state = await getProcessingRun(runId); if (state.status === 'completed') return; if (['failed', 'cancelled'].includes(state.status)) throw new Error(state.error_message ?? '任务失败'); await new Promise((resolve) => setTimeout(resolve, 1000)) } }
  const parseJd = async () => { if (!title.trim() || !jd.trim()) return; setStatus('创建项目并解析 JD...'); const project = await createRecruitmentProject(title.trim()); setProjectId(project.id); const run = await submitRecruitmentJd(project.id, jd); await waitRun(run.run_id); const parsed = await getRecruitmentProject(project.id); await confirmRecruitmentRequirements(project.id, parsed.jd_draft_payload); setStatus('JD 已解析并确认，可上传候选人') }
  const upload = async () => { if (!projectId || !files.length) return; setStatus('上传并解析候选人...'); const run = await uploadRecruitmentCandidates(projectId, files); await waitRun(run.run_id); setStatus('候选人解析完成，可开始匹配') }
  const match = async () => { if (!projectId) return; setStatus('调用 graph_match_v1.0 匹配...'); const response = await createRecruitmentMatchRun(projectId); const rows = await listRecruitmentMatchResults(projectId, response.run.id); setResult(rows); setStatus('匹配完成') }
  return <div className="page-shell page-shell--hr min-h-screen pt-14"><div className="page-shell__inner max-w-6xl mx-auto px-8 py-10"><div className="page-head page-head--archive"><FrameCorners /><div className="page-head__icon"><TeamOutlined /></div><div><div className="page-head__eyebrow">Hiring ops / real backend</div><h1 className="page-shell__title">HR 工作台</h1><p className="page-head__desc">JD 解析、候选人解析与 graph_match_v1.0 排名。</p></div></div><div className="archive-panel glass rounded-2xl p-8 max-w-3xl mx-auto space-y-5"><FrameCorners /><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="岗位名称" className="w-full bg-black/40 border border-[var(--border)] px-4 py-3 text-[var(--text)]" disabled={!!projectId} /><textarea value={jd} onChange={(e) => setJd(e.target.value)} placeholder="粘贴岗位 JD" rows={8} className="w-full bg-black/40 border border-[var(--border)] px-4 py-3 text-[var(--text)]" disabled={!!projectId} />{!projectId && <button className="btn btn-primary" onClick={() => void parseJd()} disabled={!title || !jd}>解析 JD <ArrowRightOutlined /></button>}{projectId && <><label className="console-dropzone block border border-dashed p-8 text-center cursor-pointer"><CloudUploadOutlined className="text-2xl" /><div>选择候选人简历（PDF/DOCX）</div><input type="file" multiple accept=".pdf,.docx" className="hidden" onChange={(e) => setFiles(Array.from(e.target.files ?? []))} /></label><div className="text-sm text-[var(--text-dim)]">已选择 {files.length} 份文件</div><div className="flex gap-3"><button className="btn btn-primary" onClick={() => void upload()} disabled={!files.length}>上传并解析</button><button className="btn btn-primary" onClick={() => void match()}>开始匹配</button></div></>}{result && <div className="space-y-2">{(Array.isArray(result) ? result : (result as any)?.data ?? []).map((row: any) => <div key={row.candidate_id} className="border border-white/10 p-3"><strong>#{row.rank} {row.candidate?.display_name ?? row.candidate_id}</strong><span className="ml-3 text-[#e4b592]">{row.total_score}</span><div className="text-xs text-red-300 mt-1">缺失：{(row.missing_capabilities ?? []).map((x: any) => x.canonical_name).join('、') || '无'}</div></div>)}</div>}<div className="text-sm text-[#e4b592]">{status}</div></div></div></div>
}
